Core, Backends: Fix ambiguous ArgumentOutOfRangeException constructor
Problem:
When compiling any backend, calls to the constructor of
ArgumentOutOfRangeException fails due to an ambiguous constructor.

One error message:
error: call to constructor of 'ArgumentOutOfRangeException' is ambiguous
    166 |	throw ArgumentOutOfRangeException("buffer", 0ull, buffer->size(), offset + requiredMemory, "The buffer does not contain enough memory after offset {0} to fully contain the acceleration structure.", offset);
note: candidate constructor [with T = unsigned long long, TArgs = <unsigned long long &>]
    143 |	explicit ArgumentOutOfRangeException(std::string_view argument, T fromIncluse, T toExclusive, T value, std::string_view format, TArgs&&... args) noexcept
note: candidate constructor [with TArgs = <unsigned long long, unsigned long long, const char (&)[104], unsigned long long &>]
    129 |	explicit ArgumentOutOfRangeException(std::string_view argument, std::string_view format, TArgs&&... args) noexcept

Solution:
Use a std::pair fo the value range, it allows to desambiguous the ctors
since it's now an explicit type.