Backends: Fix clang error 'member access into incomplete type'
When compiling the any backend, we have the following error:
error: member access into incomplete type 'LiteFX::Rendering::Backends::XBuilder'

So, in order to fix it, we reorder builder classes so the parent
builders are below the child ones.